artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/6ed96b15ff1a44e29f97f277f0444d85/artifacts
end_time: 1765957893340
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6ed96b15ff1a44e29f97f277f0444d85
run_name: youthful-fly-226
run_uuid: 6ed96b15ff1a44e29f97f277f0444d85
source_name: ''
source_type: 4
source_version: ''
start_time: 1765957890454
status: 3
tags: []
user_id: runner
