artifact_location: file:////home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/312626709058439667
creation_time: 1765957895366
experiment_id: '312626709058439667'
last_update_time: 1765957895366
lifecycle_stage: active
name: Heart_Disease_Classification
