artifact_location: file:////home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/130171206173030968
creation_time: 1765957939946
experiment_id: '130171206173030968'
last_update_time: 1765957939946
lifecycle_stage: active
name: Heart_Disease_Classification
