artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/6671c5572bc44ff682324c9396ebb7b5/artifacts
end_time: 1765957895024
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6671c5572bc44ff682324c9396ebb7b5
run_name: trusting-bug-408
run_uuid: 6671c5572bc44ff682324c9396ebb7b5
source_name: ''
source_type: 4
source_version: ''
start_time: 1765957892166
status: 3
tags: []
user_id: runner
