artifact_location: file:////home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/628741311099904255
creation_time: 1765957891348
experiment_id: '628741311099904255'
last_update_time: 1765957891348
lifecycle_stage: active
name: Heart_Disease_Classification
