artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0/936379fd56d64259924794f2ed2d0928/artifacts
end_time: 1765957891910
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 936379fd56d64259924794f2ed2d0928
run_name: silent-zebra-538
run_uuid: 936379fd56d64259924794f2ed2d0928
source_name: ''
source_type: 4
source_version: ''
start_time: 1765957889023
status: 3
tags: []
user_id: runner
