artifact_location: file:////home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/830732347280666342
creation_time: 1765957895411
experiment_id: '830732347280666342'
last_update_time: 1765957895411
lifecycle_stage: active
name: Heart_Disease_Classification
