artifact_location: file:////home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/703606244405378949
creation_time: 1765957894461
experiment_id: '703606244405378949'
last_update_time: 1765957894461
lifecycle_stage: active
name: Heart_Disease_Classification
