artifact_location: file:////home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/493445033211356317
creation_time: 1765957892750
experiment_id: '493445033211356317'
last_update_time: 1765957892750
lifecycle_stage: active
name: Heart_Disease_Classification
